name = "omnimanger"
main = "src/index.js"
compatibility_date = "2026-06-18"
workers_dev = true
keep_vars = true

[observability]
enabled = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "VAULT"
id = "b86d5782e8344bfe8e1a06076de34cb5"
